# Generated by Django 3.0.7 on 2020-06-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profice_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
