# Generated by Django 3.0.7 on 2020-06-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200629_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='phone',
        ),
    ]
